### ISSUE TITLE
Shortcut for changing heading level

### ISSUE THREAD

**Issue by djs070** [demon386/SmartMarkdown#13]
Hi

How about adding support to increase / decrease heading level? Maybe Cmd + Square Brackets?

I'm happy to implement the code for this if someone agrees that it's a good feature.

D

**Comment by demon386** [comment]
Hi. Good suggestion. Thanks for implementing it!

**Comment by djs070** [comment]
Added basic implementation, with keys bound to [ Cmd + Shift + , ] & [ Cmd + Shift + . ]

https://github.com/djs070/SmartMarkdown/compare/heading-levels

Should I submit pull request?
