### ISSUE TITLE
copy text by ctrl+c not working with this plugin

### ISSUE THREAD

**Issue by kutu** [demon386/SmartMarkdown#3]
for copy text now i should double press `ctrl+c`

change your hotkeys for something else

**Comment by demon386** [comment]
Thanks for pointing out. I use Mac so I didn't find this problem.

Gonna assign a new key bindings for Window and Linux user.

**Comment by mhenry07** [comment]
Perhaps it could use ctrl+, or alt+h instead of ctrl+c?

**Comment by demon386** [comment]
I assign the prefix to "ctrl+;" for headline movements in Linux and Windows. It's a little bit easier to press "ctrl+; ctrl+p" than "ctrl+. ctrl+p".
