### ISSUE TITLE
I don't get it O_O

### ISSUE THREAD

**Issue by ghost** [demon386/SmartMarkdown#6]
I guess I don't understand how to use this plugin.
I installed the plugin and tried to use it on *.txt, *.md and *.org files, but I didn't get the command pallete commands nor did the tab worked.

Can you please explain how to use the basic functionality of the plugin?
Thanks.

**Comment by demon386** [comment]
Look at the bottom right corner, see if it says "Markdown". If not, press cmd+shift+p and use the command "Set Syntax: Markdown".

It should work now. If you still have problems, try to uninstall re-install the plugin and re-launch the editor.

There have been many users so I assume that the problem doesn't lie in the plugin.

**Comment by ghost** [comment]
The issue involved two things:
1. The syntax was not markdown
2. Apparently I have to use the # headings, whereas the ----- headings doesn't work.

**Comment by detyro** [comment]
I have tried everything I can think of to get this to work. reinstalled... set file to Markdown

Whenever I press TAB all I get is the #header indenting...

I am using Sublime Text build 3065.

Nothing I do gets me near this video of SmartMarkdown in use:
https://www.youtube.com/watch?v=yXfDFtS3Tu4

Any thoughts?

**Comment by detyro** [comment]
AAAAGH

In desperation I opened Folding Text... and it mentioned about leaving a space AFTER the # BEFORE the heading text...

I previously had:

```
#heading
##2nd heading
###third heading
```

NOW I have (NOTE SPACES)

```
# heading
## 2nd heading
### third heading
```

NOW Folding is working mighty fine - thank you!!!!
