### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by swehba** [demon386/SmartMarkdown#7]
Can you provide a quick pointer for installing your add-on into Sublime Text 2? I'm new to ST2, and I have no idea how to install add-ons. It looks like, on my Mac, you drop .packages into ~\Application Support\Sublime Text 2\Packages, but the files I see there all have the .package extension, not the individual files in your git repository. Thanks.

**Comment by demon386** [comment]
The best way is to install Package Control first and install other plugins with it.

Check http://wbond.net/sublime_packages/package_control/installation for instruction.
