### ISSUE TITLE
SublimeTableEditor

### ISSUE THREAD

**Issue by alehandrof** [demon386/SmartMarkdown#8]
Is there any interest/possibility of incorporating the [SublimeTableEditor plugin](https://github.com/vkocubinsky/SublimeTableEditor)? (I am referring to the table manipulation.)

**Comment by demon386** [comment]
This plugin is doing a very good job. However, the format (e.g. separator) is not compatible with Pandoc format.

Another issue is that the plugin is licensed under GPL, while SmartMarkdown, MIT.
